In [105]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

df['job_skills']=df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if isinstance(skill_list, str) else skill_list)

In [9]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

df_fsalary=df[pd.notna(df['salary_year_avg'])].copy()

In [18]:
def fsalary (salary):
    return salary * 1.03

In [23]:
df_fsalary['fsalary']=df_fsalary['salary_year_avg'].apply(fsalary)

df_fsalary.loc[:,['salary_year_avg','fsalary']]

        salary_year_avg    fsalary
28             109500.0  112785.00
77             140000.0  144200.00
92             120000.0  123600.00
100            228222.0  235068.66
109             89000.0   91670.00
...                 ...        ...
785624         139216.0  143392.48
785641         150000.0  154500.00
785648         221875.0  228531.25
785682         157500.0  162225.00
785692         157500.0  162225.00

[22003 rows x 2 columns]

In [25]:
df_fsalary['lambda_fsalary']=df_fsalary['salary_year_avg'].apply(lambda x :x*1.03)

df_fsalary.loc[:,['salary_year_avg','fsalary','lambda_fsalary']]

        salary_year_avg    fsalary  lambda_fsalary
28             109500.0  112785.00       112785.00
77             140000.0  144200.00       144200.00
92             120000.0  123600.00       123600.00
100            228222.0  235068.66       235068.66
109             89000.0   91670.00        91670.00
...                 ...        ...             ...
785624         139216.0  143392.48       143392.48
785641         150000.0  154500.00       154500.00
785648         221875.0  228531.25       228531.25
785682         157500.0  162225.00       162225.00
785692         157500.0  162225.00       162225.00

[22003 rows x 3 columns]

In [27]:
df_fsalary['lambda_fsalary_simple']=df_fsalary['salary_year_avg']*1.03

df_fsalary.loc[:,['salary_year_avg','fsalary','lambda_fsalary','lambda_fsalary_simple']]

        salary_year_avg    fsalary  lambda_fsalary  lambda_fsalary_simple
28             109500.0  112785.00       112785.00              112785.00
77             140000.0  144200.00       144200.00              144200.00
92             120000.0  123600.00       123600.00              123600.00
100            228222.0  235068.66       235068.66              235068.66
109             89000.0   91670.00        91670.00               91670.00
...                 ...        ...             ...                    ...
785624         139216.0  143392.48       143392.48              143392.48
785641         150000.0  154500.00       154500.00              154500.00
785648         221875.0  228531.25       228531.25              228531.25
785682         157500.0  162225.00       162225.00              162225.00
785692         157500.0  162225.00       162225.00              162225.00

[22003 rows x 4 columns]

In [29]:
type(df['job_skills'][10])

str

In [ ]:
import ast

def skill_listcon(skill_list):
    if pd.notna(skill_list):
         return ast.literal_eval(skill_list)
    

df['job_skills']=df['job_skills'].apply(skill_listcon)

In [62]:
type(df['job_skills'][10])

list

In [68]:
df['job_skills']=df['job_skills'].apply(lambda skill_list: ast.literal_eval(skill_list) if isinstance(skill_list, str) else skill_list)

In [73]:
def projected_sal(row):
    if 'senior' in row['job_title_short']:
        return row['salary_year_avg']*1.05
    else:
        return row['salary_year_avg']*1.03


df_fsalary['fsalary']=df_fsalary.apply(projected_sal,axis=1)

df_fsalary.loc[:,['job_title_short','salary_year_avg','fsalary','lambda_fsalary','lambda_fsalary_simple']]

,job_title_short,salary_year_avg,fsalary,lambda_fsalary,lambda_fsalary_simple
28,Data Scientist,109500.0,112785.00,112785.00,112785.00
77,Data Engineer,140000.0,144200.00,144200.00,144200.00
92,Data Engineer,120000.0,123600.00,123600.00,123600.00
100,Data Scientist,228222.0,235068.66,235068.66,235068.66
109,Data Analyst,89000.0,91670.00,91670.00,91670.00
...,...,...,...,...,...
785624,Data Engineer,139216.0,143392.48,143392.48,143392.48
785641,Data Engineer,150000.0,154500.00,154500.00,154500.00
785648,Data Scientist,221875.0,228531.25,228531.25,228531.25
785682,Data Scientist,157500.0,162225.00,162225.00,162225.00
785692,Data Scientist,157500.0,162225.00,162225.00,162225.00

<span style ="color:green;font-width:bold;font-size:32Px;" > Practise Prompts </span>

In [78]:
# Problem Statement:
# Convert the job_posted_date column to a string format 'YYYY-MM-DD' and create a new column job_posted_date_str.

df['job_posted_date_str']=df['job_posted_date'].apply(lambda x:x.strftime('%Y-%m-%d'))

df['job_posted_date_str'].head

0         2023-06-16
1         2023-01-14
2         2023-10-10
3         2023-07-04
4         2023-08-07
             ...
785736    2023-03-13
785737    2023-03-12
785738    2023-03-12
785739    2023-03-12
785740    2023-03-13
Name: job_posted_date_str, Length: 785741, dtype: object

In [89]:
# Problem Statement:
# Calculate the number of days since each job was posted. Create a new column days_since_posted that contains this value. 
# Use the job_posted_date column.

# Note: You need to import the datetime library and use the datetime module to get the current date using .now().

import datetime as dt

current_date = dt.datetime.now() 

df['days_since_posted']= df['job_posted_date'].apply(lambda x : current_date-x)

df.loc[:,['days_since_posted','job_posted_date']]

              days_since_posted     job_posted_date
0      642 days 00:57:13.846466 2023-06-16 13:44:15
1      795 days 01:23:21.846466 2023-01-14 13:18:07
2      526 days 01:26:33.846466 2023-10-10 13:14:55
3      624 days 01:39:47.846466 2023-07-04 13:01:41
4      590 days 00:11:52.846466 2023-08-07 14:29:36
...                         ...                 ...
785736 737 days 08:25:12.846466 2023-03-13 06:16:16
785737 738 days 08:23:10.846466 2023-03-12 06:18:18
785738 738 days 08:08:52.846466 2023-03-12 06:32:36
785739 738 days 08:09:13.846466 2023-03-12 06:32:15
785740 737 days 08:24:57.846466 2023-03-13 06:16:31

[785741 rows x 2 columns]

In [127]:
# Problem Statement:
# Create a copy of the DataFrame called df_filtered and drop the NaN values for salary_year_avg.
# Then, create a new column salary_category that categorizes the salary_year_avg 
# into three categories:
# 'Low' for salaries less than 60,000, 
# 'Medium' for salaries between 60,000 and 100,000, and 
# 'High' for salaries greater than 100,000.
# Then show the df_filtered DataFrame and the salary_year_avg and salary_category columns.

df_salgroup = df.copy()


def sal_group (salary):
    if salary <=60000:
         return 'Low'
    elif salary >  60000 and  salary <= 100000:
         return 'Medium'
    else: 
        return'High'    

df_salgroup['salary_category']= df_salgroup['salary_year_avg'].apply(sal_group)


df_salgroup.head(3)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,salary_category
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None,High
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"[r, python, sql, nosql, power bi, tableau]","{'analyst_tools': ['power bi', 'tableau'], 'pr...",High
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"[python, sql, c#, azure, airflow, dax, docker,...","{'analyst_tools': ['dax'], 'cloud': ['azure'],...",High